package io.argorand.poc.dcpass.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

public class PassContractTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2L * Integer.MAX_VALUE));
    private static final AtomicInteger intCount = new AtomicInteger(random.nextInt() + (2 * Short.MAX_VALUE));

    public static PassContract getPassContractSample1() {
        return new PassContract()
            .id(1L)
            .procurementMethodDescription("procurementMethodDescription1")
            .agencyAcronym("agencyAcronym1")
            .agencyName("agencyName1")
            .rowId(1L)
            .agency("agency1")
            .contractNumber("contractNumber1")
            .contractStatus("contractStatus1")
            .title("title1")
            .contractingOfficer("contractingOfficer1")
            .fiscalYear(1)
            .marketType("marketType1")
            .commodityCode("commodityCode1")
            .commodityDescription("commodityDescription1")
            .currentOptionPeriod("currentOptionPeriod1")
            .totalOptionPeriods(1)
            .supplier("supplier1")
            .description("description1")
            .contractTypeDescription("contractTypeDescription1")
            .contractingOfficerEmail("contractingOfficerEmail1")
            .vendorAddress("vendorAddress1")
            .vendorCity("vendorCity1")
            .vendorState("vendorState1")
            .vendorZip("vendorZip1")
            .publishedVersionId("publishedVersionId1")
            .documentVersion("documentVersion1")
            .contractingSplst("contractingSplst1")
            .contractingSplstEmail("contractingSplstEmail1")
            .source("source1")
            .contractDetailsLink("contractDetailsLink1")
            .contractAdministratorName("contractAdministratorName1")
            .contractAdministratorEmail("contractAdministratorEmail1")
            .contractAdministratorPhone("contractAdministratorPhone1")
            .contractOfficerPhone("contractOfficerPhone1")
            .cwInternalId("cwInternalId1")
            .corporatePhone("corporatePhone1")
            .corporateEmailAddress("corporateEmailAddress1")
            .objectId(1L);
    }

    public static PassContract getPassContractSample2() {
        return new PassContract()
            .id(2L)
            .procurementMethodDescription("procurementMethodDescription2")
            .agencyAcronym("agencyAcronym2")
            .agencyName("agencyName2")
            .rowId(2L)
            .agency("agency2")
            .contractNumber("contractNumber2")
            .contractStatus("contractStatus2")
            .title("title2")
            .contractingOfficer("contractingOfficer2")
            .fiscalYear(2)
            .marketType("marketType2")
            .commodityCode("commodityCode2")
            .commodityDescription("commodityDescription2")
            .currentOptionPeriod("currentOptionPeriod2")
            .totalOptionPeriods(2)
            .supplier("supplier2")
            .description("description2")
            .contractTypeDescription("contractTypeDescription2")
            .contractingOfficerEmail("contractingOfficerEmail2")
            .vendorAddress("vendorAddress2")
            .vendorCity("vendorCity2")
            .vendorState("vendorState2")
            .vendorZip("vendorZip2")
            .publishedVersionId("publishedVersionId2")
            .documentVersion("documentVersion2")
            .contractingSplst("contractingSplst2")
            .contractingSplstEmail("contractingSplstEmail2")
            .source("source2")
            .contractDetailsLink("contractDetailsLink2")
            .contractAdministratorName("contractAdministratorName2")
            .contractAdministratorEmail("contractAdministratorEmail2")
            .contractAdministratorPhone("contractAdministratorPhone2")
            .contractOfficerPhone("contractOfficerPhone2")
            .cwInternalId("cwInternalId2")
            .corporatePhone("corporatePhone2")
            .corporateEmailAddress("corporateEmailAddress2")
            .objectId(2L);
    }

    public static PassContract getPassContractRandomSampleGenerator() {
        return new PassContract()
            .id(longCount.incrementAndGet())
            .procurementMethodDescription(UUID.randomUUID().toString())
            .agencyAcronym(UUID.randomUUID().toString())
            .agencyName(UUID.randomUUID().toString())
            .rowId(longCount.incrementAndGet())
            .agency(UUID.randomUUID().toString())
            .contractNumber(UUID.randomUUID().toString())
            .contractStatus(UUID.randomUUID().toString())
            .title(UUID.randomUUID().toString())
            .contractingOfficer(UUID.randomUUID().toString())
            .fiscalYear(intCount.incrementAndGet())
            .marketType(UUID.randomUUID().toString())
            .commodityCode(UUID.randomUUID().toString())
            .commodityDescription(UUID.randomUUID().toString())
            .currentOptionPeriod(UUID.randomUUID().toString())
            .totalOptionPeriods(intCount.incrementAndGet())
            .supplier(UUID.randomUUID().toString())
            .description(UUID.randomUUID().toString())
            .contractTypeDescription(UUID.randomUUID().toString())
            .contractingOfficerEmail(UUID.randomUUID().toString())
            .vendorAddress(UUID.randomUUID().toString())
            .vendorCity(UUID.randomUUID().toString())
            .vendorState(UUID.randomUUID().toString())
            .vendorZip(UUID.randomUUID().toString())
            .publishedVersionId(UUID.randomUUID().toString())
            .documentVersion(UUID.randomUUID().toString())
            .contractingSplst(UUID.randomUUID().toString())
            .contractingSplstEmail(UUID.randomUUID().toString())
            .source(UUID.randomUUID().toString())
            .contractDetailsLink(UUID.randomUUID().toString())
            .contractAdministratorName(UUID.randomUUID().toString())
            .contractAdministratorEmail(UUID.randomUUID().toString())
            .contractAdministratorPhone(UUID.randomUUID().toString())
            .contractOfficerPhone(UUID.randomUUID().toString())
            .cwInternalId(UUID.randomUUID().toString())
            .corporatePhone(UUID.randomUUID().toString())
            .corporateEmailAddress(UUID.randomUUID().toString())
            .objectId(longCount.incrementAndGet());
    }
}
