package io.argorand.poc.dcpass.domain;

import static io.argorand.poc.dcpass.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PassPaymentAsserts {

    public static void assertPassPaymentAllPropertiesEquals(PassPayment expected, PassPayment actual) {
        assertPassPaymentAutoGeneratedPropertiesEquals(expected, actual);
        assertPassPaymentAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertPassPaymentAllUpdatablePropertiesEquals(PassPayment expected, PassPayment actual) {
        assertPassPaymentUpdatableFieldsEquals(expected, actual);
        assertPassPaymentUpdatableRelationshipsEquals(expected, actual);
    }

    public static void assertPassPaymentAutoGeneratedPropertiesEquals(PassPayment expected, PassPayment actual) {
        assertThat(actual)
            .as("Verify PassPayment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    public static void assertPassPaymentUpdatableFieldsEquals(PassPayment expected, PassPayment actual) {
        assertThat(actual)
            .as("Verify PassPayment relevant properties")
            .satisfies(a -> assertThat(a.getAgencyCode()).as("check agencyCode").isEqualTo(expected.getAgencyCode()))
            .satisfies(a -> assertThat(a.getAgencyAcronym()).as("check agencyAcronym").isEqualTo(expected.getAgencyAcronym()))
            .satisfies(a -> assertThat(a.getAgencyName()).as("check agencyName").isEqualTo(expected.getAgencyName()))
            .satisfies(a -> assertThat(a.getContractNumber()).as("check contractNumber").isEqualTo(expected.getContractNumber()))
            .satisfies(a -> assertThat(a.getSupplierName()).as("check supplierName").isEqualTo(expected.getSupplierName()))
            .satisfies(a -> assertThat(a.getInvoiceNumber()).as("check invoiceNumber").isEqualTo(expected.getInvoiceNumber()))
            .satisfies(a -> assertThat(a.getPoNumber()).as("check poNumber").isEqualTo(expected.getPoNumber()))
            .satisfies(a -> assertThat(a.getVoucherNumber()).as("check voucherNumber").isEqualTo(expected.getVoucherNumber()))
            .satisfies(a -> assertThat(a.getPaymentDate()).as("check paymentDate").isEqualTo(expected.getPaymentDate()))
            .satisfies(a ->
                assertThat(a.getPaymentAmount())
                    .as("check paymentAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPaymentAmount())
            )
            .satisfies(a -> assertThat(a.getFiscalYear()).as("check fiscalYear").isEqualTo(expected.getFiscalYear()))
            .satisfies(a -> assertThat(a.getTransactionCode()).as("check transactionCode").isEqualTo(expected.getTransactionCode()))
            .satisfies(a -> assertThat(a.getPaymentType()).as("check paymentType").isEqualTo(expected.getPaymentType()))
            .satisfies(a -> assertThat(a.getInvoiceDate()).as("check invoiceDate").isEqualTo(expected.getInvoiceDate()))
            .satisfies(a -> assertThat(a.getEstPaymentDate()).as("check estPaymentDate").isEqualTo(expected.getEstPaymentDate()))
            .satisfies(a -> assertThat(a.getPaymentNumber()).as("check paymentNumber").isEqualTo(expected.getPaymentNumber()))
            .satisfies(a -> assertThat(a.getRecordUpdatedDate()).as("check recordUpdatedDate").isEqualTo(expected.getRecordUpdatedDate()))
            .satisfies(a -> assertThat(a.getRecordCreated()).as("check recordCreated").isEqualTo(expected.getRecordCreated()))
            .satisfies(a -> assertThat(a.getDcsRecCrtDttm()).as("check dcsRecCrtDttm").isEqualTo(expected.getDcsRecCrtDttm()))
            .satisfies(a -> assertThat(a.getDcsLastModDttm()).as("check dcsLastModDttm").isEqualTo(expected.getDcsLastModDttm()))
            .satisfies(a -> assertThat(a.getObjectId()).as("check objectId").isEqualTo(expected.getObjectId()));
    }

    public static void assertPassPaymentUpdatableRelationshipsEquals(PassPayment expected, PassPayment actual) {
        // empty method
    }
}
