package io.argorand.poc.dcpass.domain;

import static io.argorand.poc.dcpass.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PassContractAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassContractAllPropertiesEquals(PassContract expected, PassContract actual) {
        assertPassContractAutoGeneratedPropertiesEquals(expected, actual);
        assertPassContractAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassContractAllUpdatablePropertiesEquals(PassContract expected, PassContract actual) {
        assertPassContractUpdatableFieldsEquals(expected, actual);
        assertPassContractUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassContractAutoGeneratedPropertiesEquals(PassContract expected, PassContract actual) {
        assertThat(actual)
            .as("Verify PassContract auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassContractUpdatableFieldsEquals(PassContract expected, PassContract actual) {
        assertThat(actual)
            .as("Verify PassContract relevant properties")
            .satisfies(a ->
                assertThat(a.getProcurementMethodDescription())
                    .as("check procurementMethodDescription")
                    .isEqualTo(expected.getProcurementMethodDescription())
            )
            .satisfies(a -> assertThat(a.getAgencyAcronym()).as("check agencyAcronym").isEqualTo(expected.getAgencyAcronym()))
            .satisfies(a -> assertThat(a.getAgencyName()).as("check agencyName").isEqualTo(expected.getAgencyName()))
            .satisfies(a -> assertThat(a.getRowId()).as("check rowId").isEqualTo(expected.getRowId()))
            .satisfies(a -> assertThat(a.getAgency()).as("check agency").isEqualTo(expected.getAgency()))
            .satisfies(a -> assertThat(a.getAwardDate()).as("check awardDate").isEqualTo(expected.getAwardDate()))
            .satisfies(a ->
                assertThat(a.getContractAmount())
                    .as("check contractAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getContractAmount())
            )
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getContractNumber()).as("check contractNumber").isEqualTo(expected.getContractNumber()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getContractStatus()).as("check contractStatus").isEqualTo(expected.getContractStatus()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a ->
                assertThat(a.getContractingOfficer()).as("check contractingOfficer").isEqualTo(expected.getContractingOfficer())
            )
            .satisfies(a -> assertThat(a.getFiscalYear()).as("check fiscalYear").isEqualTo(expected.getFiscalYear()))
            .satisfies(a -> assertThat(a.getMarketType()).as("check marketType").isEqualTo(expected.getMarketType()))
            .satisfies(a -> assertThat(a.getCommodityCode()).as("check commodityCode").isEqualTo(expected.getCommodityCode()))
            .satisfies(a ->
                assertThat(a.getCommodityDescription()).as("check commodityDescription").isEqualTo(expected.getCommodityDescription())
            )
            .satisfies(a ->
                assertThat(a.getCurrentOptionPeriod()).as("check currentOptionPeriod").isEqualTo(expected.getCurrentOptionPeriod())
            )
            .satisfies(a ->
                assertThat(a.getTotalOptionPeriods()).as("check totalOptionPeriods").isEqualTo(expected.getTotalOptionPeriods())
            )
            .satisfies(a -> assertThat(a.getSupplier()).as("check supplier").isEqualTo(expected.getSupplier()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getContractTypeDescription())
                    .as("check contractTypeDescription")
                    .isEqualTo(expected.getContractTypeDescription())
            )
            .satisfies(a ->
                assertThat(a.getContractingOfficerEmail())
                    .as("check contractingOfficerEmail")
                    .isEqualTo(expected.getContractingOfficerEmail())
            )
            .satisfies(a -> assertThat(a.getVendorAddress()).as("check vendorAddress").isEqualTo(expected.getVendorAddress()))
            .satisfies(a -> assertThat(a.getVendorCity()).as("check vendorCity").isEqualTo(expected.getVendorCity()))
            .satisfies(a -> assertThat(a.getVendorState()).as("check vendorState").isEqualTo(expected.getVendorState()))
            .satisfies(a -> assertThat(a.getVendorZip()).as("check vendorZip").isEqualTo(expected.getVendorZip()))
            .satisfies(a ->
                assertThat(a.getPublishedVersionId()).as("check publishedVersionId").isEqualTo(expected.getPublishedVersionId())
            )
            .satisfies(a -> assertThat(a.getDocumentVersion()).as("check documentVersion").isEqualTo(expected.getDocumentVersion()))
            .satisfies(a -> assertThat(a.getLastModified()).as("check lastModified").isEqualTo(expected.getLastModified()))
            .satisfies(a -> assertThat(a.getContractingSplst()).as("check contractingSplst").isEqualTo(expected.getContractingSplst()))
            .satisfies(a ->
                assertThat(a.getContractingSplstEmail()).as("check contractingSplstEmail").isEqualTo(expected.getContractingSplstEmail())
            )
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a ->
                assertThat(a.getContractDetailsLink()).as("check contractDetailsLink").isEqualTo(expected.getContractDetailsLink())
            )
            .satisfies(a ->
                assertThat(a.getContractAdministratorName())
                    .as("check contractAdministratorName")
                    .isEqualTo(expected.getContractAdministratorName())
            )
            .satisfies(a ->
                assertThat(a.getContractAdministratorEmail())
                    .as("check contractAdministratorEmail")
                    .isEqualTo(expected.getContractAdministratorEmail())
            )
            .satisfies(a ->
                assertThat(a.getContractAdministratorPhone())
                    .as("check contractAdministratorPhone")
                    .isEqualTo(expected.getContractAdministratorPhone())
            )
            .satisfies(a ->
                assertThat(a.getContractOfficerPhone()).as("check contractOfficerPhone").isEqualTo(expected.getContractOfficerPhone())
            )
            .satisfies(a -> assertThat(a.getCwInternalId()).as("check cwInternalId").isEqualTo(expected.getCwInternalId()))
            .satisfies(a -> assertThat(a.getCorporatePhone()).as("check corporatePhone").isEqualTo(expected.getCorporatePhone()))
            .satisfies(a ->
                assertThat(a.getCorporateEmailAddress()).as("check corporateEmailAddress").isEqualTo(expected.getCorporateEmailAddress())
            )
            .satisfies(a -> assertThat(a.getRecCreatedDate()).as("check recCreatedDate").isEqualTo(expected.getRecCreatedDate()))
            .satisfies(a -> assertThat(a.getRecUpdatedDate()).as("check recUpdatedDate").isEqualTo(expected.getRecUpdatedDate()))
            .satisfies(a -> assertThat(a.getDcsLastModDttm()).as("check dcsLastModDttm").isEqualTo(expected.getDcsLastModDttm()))
            .satisfies(a -> assertThat(a.getObjectId()).as("check objectId").isEqualTo(expected.getObjectId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassContractUpdatableRelationshipsEquals(PassContract expected, PassContract actual) {
        // empty method
    }
}
