package io.argorand.poc.dcpass.domain;

import static io.argorand.poc.dcpass.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PurchaseOrderAsserts {

    public static void assertPurchaseOrderAllPropertiesEquals(PurchaseOrder expected, PurchaseOrder actual) {
        assertPurchaseOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertPurchaseOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertPurchaseOrderAllUpdatablePropertiesEquals(PurchaseOrder expected, PurchaseOrder actual) {
        assertPurchaseOrderUpdatableFieldsEquals(expected, actual);
        assertPurchaseOrderUpdatableRelationshipsEquals(expected, actual);
    }

    public static void assertPurchaseOrderAutoGeneratedPropertiesEquals(PurchaseOrder expected, PurchaseOrder actual) {
        assertThat(actual)
            .as("Verify PurchaseOrder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    public static void assertPurchaseOrderUpdatableFieldsEquals(PurchaseOrder expected, PurchaseOrder actual) {
        assertThat(actual)
            .as("Verify PurchaseOrder relevant properties")
            .satisfies(a -> assertThat(a.getPoNumber()).as("check poNumber").isEqualTo(expected.getPoNumber()))
            .satisfies(a -> assertThat(a.getAgencyCode()).as("check agencyCode").isEqualTo(expected.getAgencyCode()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getRequester()).as("check requester").isEqualTo(expected.getRequester()))
            .satisfies(a -> assertThat(a.getRequisitionNumber()).as("check requisitionNumber").isEqualTo(expected.getRequisitionNumber()))
            .satisfies(a -> assertThat(a.getCommodityCode()).as("check commodityCode").isEqualTo(expected.getCommodityCode()))
            .satisfies(a -> assertThat(a.getCommodityName()).as("check commodityName").isEqualTo(expected.getCommodityName()))
            .satisfies(a -> assertThat(a.getContractNumber()).as("check contractNumber").isEqualTo(expected.getContractNumber()))
            .satisfies(a -> assertThat(a.getSupplier()).as("check supplier").isEqualTo(expected.getSupplier()))
            .satisfies(a -> assertThat(a.getOrderedDate()).as("check orderedDate").isEqualTo(expected.getOrderedDate()))
            .satisfies(a -> assertThat(a.getCreateDate()).as("check createDate").isEqualTo(expected.getCreateDate()))
            .satisfies(a ->
                assertThat(a.getPoTotal()).as("check poTotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPoTotal())
            )
            .satisfies(a -> assertThat(a.getFiscalYear()).as("check fiscalYear").isEqualTo(expected.getFiscalYear()))
            .satisfies(a -> assertThat(a.getPoTitle()).as("check poTitle").isEqualTo(expected.getPoTitle()))
            .satisfies(a -> assertThat(a.getAgencyAcronym()).as("check agencyAcronym").isEqualTo(expected.getAgencyAcronym()))
            .satisfies(a -> assertThat(a.getAgencyName()).as("check agencyName").isEqualTo(expected.getAgencyName()))
            .satisfies(a -> assertThat(a.getDcsLastModDttm()).as("check dcsLastModDttm").isEqualTo(expected.getDcsLastModDttm()))
            .satisfies(a -> assertThat(a.getDcsRecCrtDttm()).as("check dcsRecCrtDttm").isEqualTo(expected.getDcsRecCrtDttm()))
            .satisfies(a -> assertThat(a.getObjectId()).as("check objectId").isEqualTo(expected.getObjectId()));
    }

    public static void assertPurchaseOrderUpdatableRelationshipsEquals(PurchaseOrder expected, PurchaseOrder actual) {
        // empty method
    }
}
